### ISSUE TITLE
GraphQL error on develop

### ISSUE THREAD

**Issue by thomasfaller** [cosmicjs/gatsby-source-cosmicjs#16]
Hey folks,

Hope everyone is safe home and virus-free 🤞🏻

I started a new CosmicJs project and when I type `gatsby develop` I get the following output :

```bash
success open and validate gatsby-configs - 0.044s
success load plugins - 0.516s
success onPreInit - 0.004s
success initialize cache - 0.014s
success copy gatsby files - 0.104s
success onPreBootstrap - 0.027s
success createSchemaCustomization - 0.008s
Starting to fetch data from Cosmic JS (posts)
Starting to fetch data from Cosmic JS (settings)

 ERROR 

(node:6745) Warning: Label 'Fetch Cosmic JS data' already exists for console.time()


 ERROR #11321  PLUGIN

"gatsby-source-cosmicjs" threw an error while running the sourceNodes lifecycle:

Request failed with status code 404



  Error: Request failed with status code 404
  
  - createError.js:16 createError
    [tomthedev-gatsby-cosmic]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:17 settle
    [tomthedev-gatsby-cosmic]/[axios]/lib/core/settle.js:17:12
  
  - http.js:237 IncomingMessage.handleStreamEnd
    [tomthedev-gatsby-cosmic]/[axios]/lib/adapters/http.js:237:11
  
  - task_queues.js:84 processTicksAndRejections
    internal/process/task_queues.js:84:21
  

warn The gatsby-source-cosmicjs plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.379s
warn Plugin `gatsby-source-filesystem` tried to define built-in Gatsby GraphQL type `File`
success building schema - 0.264s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allCosmicjsPosts" on type "Query".

If you don't expect "allCosmicjsPosts" to exist on the type "Query" it is most likely a typo.
However, if you expect "allCosmicjsPosts" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allCosmicjsPosts" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: gatsby-node.js:13:10

[
  GraphQLError: Cannot query field "allCosmicjsPosts" on type "Query".
      at Object.Field (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)
      at Object.enter (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/graphql/language/visitor.js:324:29)
      at Object.enter (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/graphql/language/visitor.js:375:25)
      at visit (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/graphql/language/visitor.js:242:26)
      at validate (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/graphql/validation/validate.js:73:24)
      at GraphQLRunner.validate (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/dist/query/graphql-runner.js:53:44)
      at GraphQLRunner.query (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/dist/query/graphql-runner.js:78:25)
      at /Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/dist/bootstrap/graphql-runner.js:21:37
      at /Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/gatsby-node.js:16:7
      at Promise._execute (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/bluebird/js/release/promise.js:488:18)
      at new Promise (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/bluebird/js/release/promise.js:79:10)
      at Object.exports.createPages (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/gatsby-node.js:13:10)
      at runAPI (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/dist/utils/api-runner-node.js:252:37)
      at Promise.catch.decorateEvent.pluginName (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/dist/utils/api-runner-node.js:371:15)
      at Promise._execute (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:103:10)
      at /Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/dist/utils/api-runner-node.js:370:12
      at tryCatcher (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/node_modules/gatsby/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    message: 'Cannot query field "allCosmicjsPosts" on type "Query".',
    locations: [ [Object] ]
  }
]

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot read property 'allCosmicjsPosts' of undefined

  34 | 
  35 |         // Create blog posts pages.
> 36 |         const posts = result.data.allCosmicjsPosts.edges;
     |                                   ^
  37 | 
  38 |         each(posts, (post, index) => {
  39 |           const next = index === posts.length - 1 ? null : posts[index + 1].node;

File: gatsby-node.js:36:35



  TypeError: Cannot read property 'allCosmicjsPosts' of undefined
  
  - gatsby-node.js:36 
    /Users/thomas/Dev/Projects/portfolio-project/tomthedev-gatsby-cosmic/gatsby-node.js:36:35
  

failed createPages - 0.111s
success createPagesStatefully - 0.145s
success onPreExtractQueries - 0.002s
success update schema - 0.052s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allCosmicjsPosts" on type "Query".

If you don't expect "allCosmicjsPosts" to exist on the type "Query" it is most likely a typo.
However, if you expect "allCosmicjsPosts" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allCosmicjsPosts" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/pages/index.js:54:5


 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "cosmicjsSettings" on type "Query".

If you don't expect "cosmicjsSettings" to exist on the type "Query" it is most likely a typo.
However, if you expect "cosmicjsSettings" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "cosmicjsSettings" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/pages/index.js:66:5


 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "cosmicjsSettings" on type "Query".

If you don't expect "cosmicjsSettings" to exist on the type "Query" it is most likely a typo.
However, if you expect "cosmicjsSettings" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "cosmicjsSettings" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/components/layout.js:17:9


 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "cosmicjsPosts" on type "Query".

If you don't expect "cosmicjsPosts" to exist on the type "Query" it is most likely a typo.
However, if you expect "cosmicjsPosts" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "cosmicjsPosts" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/templates/blog-post.js:124:5


 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "cosmicjsSettings" on type "Query".

If you don't expect "cosmicjsSettings" to exist on the type "Query" it is most likely a typo.
However, if you expect "cosmicjsSettings" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "cosmicjsSettings" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/templates/blog-post.js:135:5

failed extract queries from components - 0.301s
success write out requires - 0.044s
success write out redirect data - 0.002s
success onPostBootstrap - 0.002s
⠀
info bootstrap finished - 7.570 s
⠀
success run queries - 0.057s - 5/5 87.84/s
⠀
You can now view gatsby-blog-cosmicjs in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 3.243s
```

My `package.json`

```json
{
  "name": "gatsby-blog-cosmicjs",
  "description": "Gatsby Blog Cosmic JS",
  "version": "2.0.0",
  "author": "Jazib Sawar <jazibsawar@gmail.com>",
  "bugs": {
    "url": "https://github.com/jazibsawar/gatsby-blog-cosmicjs/issues"
  },
  "dependencies": {
    "dotenv": "^8.2.0",
    "gatsby": "^2.19.44",
    "gatsby-plugin-google-analytics": "^2.1.16",
    "gatsby-plugin-offline": "^3.0.7",
    "gatsby-plugin-react-helmet": "^3.1.7",
    "gatsby-plugin-typography": "^2.3.7",
    "gatsby-source-cosmicjs": "^1.0.1",
    "gatsby-source-filesystem": "^2.1.24",
    "lodash": "^4.17.15",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-helmet": "^5.2.1",
    "react-typography": "^0.16.19",
    "typeface-merriweather": "0.0.72",
    "typeface-montserrat": "0.0.75",
    "typography": "^0.16.19",
    "typography-theme-wordpress-2016": "^0.16.19"
  },
  "devDependencies": {
    "eslint": "^6.4.0",
    "eslint-plugin-react": "^7.14.3",
    "prettier": "^1.18.2"
  },
  "homepage": "https://github.com/gatsbyjs/gatsby-starter-blog#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
  },
  "scripts": {
    "start": "gatsby build; gatsby serve --port $PORT",
    "dev": "gatsby develop",
    "lint": "./node_modules/.bin/eslint --ext .js,.jsx --ignore-pattern public .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js' 'src/**/*.md'",
    "develop": "gatsby develop",
    "build": "gatsby build",
    "fix-semi": "eslint --quiet --ignore-pattern node_modules --ignore-pattern public --parser babel-eslint --no-eslintrc --rule '{\"semi\": [2, \"never\"], \"no-extra-semi\": [2]}' --fix gatsby-node.js"
  }
}

```

I have a `.env` file populated with `GITHUB_TOKEN, COSMIC_BUCKET and COSMIC_READ_KEY`

Any thoughts on what I'm doing wrong ?

**Comment by jazibsawar** [comment]
@thomasfaller Hope you're safe and doing great. By default, gatsby doesn't support `dotenv` integration. To use it, follow instructions here https://www.gatsbyjs.org/docs/environment-variables/.
Or for development purposes, you can hardcode values in `gatsby-config.js`.
